name: Security Audit
on:
  schedule:
    # - cron: '0 0 * * *'  # Runs daily at midnight
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan For Vulnerabilities
        run: cargo deny check advisories

